### ISSUE TITLE
ParameterTest expect with char * literals works not for string

### ISSUE THREAD

**Issue by dhaeb** [IngoRoessner/LTest#17]
Hey,
instread of 
```cpp
test.with(var1).expect("hallo"); // does not work if the function under test returns a string (for ParameterTest<string, ...>)
```
I need to write: 
```cpp
test.with(var1).expect(string("hallo")); // works in the moment
```
in order to compile the code. 
It is because the compiler can not explicitly infer that I want the coercion of char * to string.
Can we make him to do so? Because to compare char *  with another char * is really seldom and only useful for identity tests. Maybe add a explicit template for expect parameter like:
```cpp
test.with(var1).expect<string>("hallo"); // not implemented yet
```
At least we need to document that.

**Comment by IngoRoessner** [comment]
replace expect() with validate() when using functions
